#!/bin/bash

#crontab -e: editar o arquivo atual ou criar um, caso não exista
#crontab -l: listar suas tarefas programadas
#crontab -r: remover uma tarefa programada
# ver logs do crontab: $ grep CRON /var/log/syslog

## teste
37 11 * * * /home/alfredo/scripts/backupvms.sh
35 11 * * * /home/alfredo/scripts/compactvms.sh
30 11 * * * /home/alfredo/scripts/deletesnapshots.sh 3
27 11 * * * /home/alfredo/scripts/createsnapshots.sh


## producao
## executa todos os dias às 1h
00 1 * * * /home/alfredo/scripts/backupvms.sh
## executa todos os dias às 0h30
30 0 * * * /home/alfredo/scripts/compactvms.sh
## executa todos os domingo às 3h
00 3 * * 0 /home/alfredo/scripts/deletesnapshots.sh 7
## executa a cada 1h de cada dia
00 */1 * * * /home/alfredo/scripts/createsnapshots.sh